query Galleries {
  galleries {
    edges {
      node {
        title
        id
        slug
        acfgallery {
          title
          image {
            sourceUrl
            altText
          }
        }
      }
    }
  }
}
