query last3postsFa {
  posts(
    first: 3
    where: {orderby: {field: DATE, order: DESC}, categoryNotIn: [6], categoryIn: [5]}
  ) {
    edges {
      node {
        id
        title
        slug
        date
        excerpt
        featuredImage {
          node {
            altText
            sourceUrl
          }
        }
      }
    }
  }
}