query PostsFa($first: Int, $after: String) {
  posts(first: $first, after: $after ,where:{categoryNotIn:[6]  categoryIn:[5]} ){
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      endCursor
      startCursor
      offsetPagination {
        hasMore
        hasPrevious
        total
      }
    }
    edges {
      cursor
      node {
        databaseId
        title
        slug
        excerpt
        featuredImage {
          node {
            sourceUrl
          }
        }
      }
    }
  }
}